export const types = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	FETCH_POKEMONS_START: "FETCH_POKEMONS_START",
  FETCH_POKEMONS_SUCCESS: "FETCH_POKEMONS_SUCCESS",
  FETCH_POKEMONS_FAILURE: "FETCH_POKEMONS_FAILURE",
	FETCH_POKEMONS_LIST_START: "FETCH_POKEMONS_LIST_START",
  FETCH_POKEMONS_LIST_SUCCESS: "FETCH_POKEMONS_LIST_SUCCESS",
  FETCH_POKEMONS_LIST_FAILURE: "FETCH_POKEMONS_LIST_FAILURE"
}
